---
network:
  host: ircserver
  port: 6667
  password: ""
  sasl: false
  nick: Modubot
  username: Modubot
  realname: Modubot
  channels: []

bot:
  command: .
  debug: true
  admins: []

plugins:
  - kamaln7/ping

database:
  mongodb: mongodb://localhost/modubot

plugin:
  kamaln7/webserver:
    port: 8888
  kamaln7/wolframalpha:
    applicationId: Get an application ID from http://products.wolframalpha.com/developers/
  kamaln7/weather:
    appId: Yahoo! App ID
  axxim/factoids:
    command: ?
